#!/usr/bin/env bash
# Point sub-domain to load balancer

domain_information () {
    local domain="$1"
    local subdomain="$2"

    # Retrieve DNS information for the subdomain
    local result=$(dig +short "${subdomain}.${domain}")
    local record_type=$(dig "${subdomain}.${domain}" | awk '/ANSWER SECTION/ {getline; print $4}')

    # Print the information if DNS record exists
    if [ -n "$result" ]; then
        echo "The subdomain ${subdomain} is a ${record_type} record and points to ${result}"
    fi
}

# Check if domain argument is provided
if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

# If only domain is provided, display information for all subdomains
if [ $# -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ $# -eq 2 ]; then
    domain_information "$1" "$2"
fi
