#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get update
sudo apt-get install -y nginx
echo 'Hello World!' | sudo tee /var/www/html/
sudo ufw allow "Nginx HTTP"
sudo service nginx start