#!/usr/bin/env bash
# Configure Nginx for custom 404 page

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Define the content for the custom 404 page
CUSTOM_404_CONTENT="Ceci n'est pas une page"

# Check if custom 404 page needs configuration
if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-available/default || ! grep -q "$CUSTOM_404_CONTENT" /var/www/html/404.html
then
    # Add custom 404 page configuration using sed
    sudo sed -i '/listen 80 default_server/a \
    \    error_page 404 /404.html;\n\
    \    location = /404.html {\n\
    \        internal;\n\
    \        root /var/www/html;\n\
    \    }\n' /etc/nginx/sites-available/default

    # Create or update the custom 404 page with the specified content
    echo "$CUSTOM_404_CONTENT" | sudo tee /var/www/html/404.html > /dev/null

    # Test Nginx configuration
    sudo nginx -t

    # Restart Nginx to apply changes
    sudo systemctl restart nginx
fi
