#!/usr/bin/env bash
# Display given string using if and while loop
# startpoint = Loop counter
startpoint=0

while [ $startpoint -lt 10 ]
do
	if [ $startpoint -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	startpoint=$(( startpoint +1 ))
done
