#!/usr/bin/env bash
# Bash script demonstrating the use of File test operators
# loop through each file in the current directory

for file in *;
do
	if [[ ! "$file" == .* && -f "$file" ]]; then
		new_names=$(echo "$file" | cut -d'-' -f2)
		echo "$new_names"
	fi
done
