#!/usr/bin/env bash
# configures an ubuntu server to resolve localhost to 127.0.0.2
# and  facebook.com to 8.8.8.8.

cp /etc/hosts ~/hosts.back_up

sed -i 's/^127.0.0.1 localhost/127.0.0.2 localhost/g' /hosts.back_up
echo "8.8.8.8 facebook.com" >> /hosts.back_up

cp -f ~/hosts.back_up /etc/hosts